project: fabric

logging: INFO
network: HLF
tls: 'false'
crypto: fastfabric_exp/organizations
artifacts: fastfabric_exp/channel-artifacts

peers: 
  image: hyperledger/fabric-peer:fastfabricv1.0
  template: peer
  count: 6
  bootstrap: 0

orderer:
  name: orderer
  image: hyperledger/fabric-orderer:fastfabricv1.0
  host: node4.bidl.bidl-pg0.utah.cloudlab.us

cli:
  name: cli
  image: hyperledger/fabric-tools:fastfabricv1.0
  host: node0.bidl.bidl-pg0.utah.cloudlab.us
  chaincode: fastfabric_exp/chaincode
  scripts: fastfabric_exp/scripts

tape:
  name: tape
  image: tape:latest
  host: node0.bidl.bidl-pg0.utah.cloudlab.us
  config: fastfabric_exp/tape.yaml
  organizations: fastfabric_exp/organizations

hosts:
  - node1.bidl.bidl-pg0.utah.cloudlab.us
  - node1.bidl.bidl-pg0.utah.cloudlab.us
  - node2.bidl.bidl-pg0.utah.cloudlab.us
  - node2.bidl.bidl-pg0.utah.cloudlab.us
  - node3.bidl.bidl-pg0.utah.cloudlab.us
  - node3.bidl.bidl-pg0.utah.cloudlab.us
  - heming-rdma4
  - heming-rdma6
  - heming-rdma8
  - heming-rdma9
  - heming-rdma3
  - heming-rdma19
  - heming-rdma9
  - heming-rdma3
  - heming-rdma4
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma19
