project: fabric

logging: INFO
network: HLF
tls: 'false'
crypto: fastfabric_exp/organizations
artifacts: fastfabric_exp/channel-artifacts

peers: 
  image: hyperledger/fabric-peer:fastfabric-v1.0 # TODO: fastfabric-2phase
  template: peer
  count: 6
  bootstrap: 0

orderer:
  name: orderer
  image: hyperledger/fabric-orderer:fastfabric-v3.0 
  host: heming-rdma6

cli:
  name: cli
  image: hyperledger/fabric-tools:fastfabric-v1.0
  host: heming-rdma2 # deprecated
  chaincode: fastfabric_exp/chaincode
  scripts: fastfabric_exp/scripts

tape:
  name: tape
  image: tape:latest
  host: heming-rdma2 # deprecated
  config: fastfabric_exp/tape.yaml
  organizations: fastfabric_exp/organizations

hosts:
  - heming-rdma3
  - heming-rdma4
  - heming-rdma5
  - heming-rdma3
  - heming-rdma9
  - heming-rdma19
  - heming-rdma9
  - heming-rdma3
  - heming-rdma4
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma3
  - heming-rdma4
  - heming-rdma9
  - heming-rdma6
  - heming-rdma19
