---
- import_playbook: helper/env.yml
- import_playbook: helper/load_state.yml

- hosts: localhost
  tasks:
    - file:
        path: "{{ (workdir, 'remote') | path_join }}"
        state: directory

- name: fetch files from the remote
  hosts: "{{ ngroup }}"
  tasks:
    - import_tasks: helper/fetch.yml
  vars:
    workdir: "{{ hostvars['localhost']['workdir'] }}"
    last_state: "{{ hostvars['localhost']['last_state'] }}"
    nid: "{{ host_idx | default(0) }}"
    ngroup: "{{ node_group | default('nodes') }}"
    testbed: "{{ (testbed_prefix, run_id, nid, '') | path_join }}"
