---
- import_playbook: helper/env.yml
- import_playbook: helper/load_state.yml

- hosts: localhost
  tasks:
    - file:
        path: "{{ workdir }}"
        state: directory
    - name: check the state status
      fail: msg="nodes are already started"
      when: last_state['status']  == "started" and not(forced|default(false)|bool)

- name: start the nodes
  hosts: "{{ ngroup }}"
  tasks:
    - import_tasks: "{{ run_tasks | default('../app/run.yml') }}"
  vars:
    last_state: "{{ hostvars['localhost']['last_state'] }}"
    nid: "{{ host_idx | default(0) }}"
    ngroup: "{{ node_group | default('nodes') }}"
    testbed: "{{ (testbed_prefix, run_id, nid, '') | path_join }}"

- hosts: localhost
  tasks:
    - set_fact:
        cur_state: "{{ last_state | combine({'status': 'started'}) }}"
- import_playbook: helper/update_spawn_state.yml
  vars:
    ngroup: "{{ node_group | default('nodes') }}"
- import_playbook: helper/save_state.yml
