---
- import_playbook: helper/env.yml
- import_playbook: helper/load_state.yml

- hosts: localhost
  tasks:
    - name: check the state status
      fail: msg="nodes are not running"
      when: last_state['status']  != "started"

- name: stop all nodes
  hosts: "{{ ngroup }}"
  tasks:
    - import_tasks: helper/stop.yml
  vars:
    last_state: "{{ hostvars['localhost']['last_state'] }}"
    nid: "{{ host_idx | default(0) }}"
    ngroup: "{{ node_group | default('nodes') }}"
    testbed: "{{ (testbed_prefix, run_id, nid, '') | path_join }}"

- hosts: localhost
  tasks:
    - set_fact:
        cur_state: "{{ last_state | combine({'status': 'stopped'}) }}"
- import_playbook: helper/save_state.yml
