---
# available vars:
# last_state -- the content of state.json
# nid -- host_idx (with 0 as default)
# ngroup -- the group of nodes involved in the build
# testbed -- the remote path of run_id

- name: build json-server
  shell:
    cmd: npm install -g json-server
  become: true
  become_user: root
